scripts/scripts.js

This PR adds templating mechanism which we'd have to use variety of templates available and not putting all things in Global styles and scripts
I added article folder /templates with it's distinct css and js to reflect the feature on the sample page. Sample page has a metadata 'template=article' and once the page is loaded should load the article template with it's distinct css and js.
---
Fix #23 
Test URLs:
- Before: https://main--cmegroup--aemsites.aem.page/drafts/kunwar/q1-dairy-market-outlook
- After: https://issue-23-template--cmegroup--aemsites.aem.page/drafts/kunwar/q1-dairy-market-outlook

[feature] - Templating

---

blocks/columns/columns.css
blocks/hero/hero.css
blocks/hero/hero.js
scripts/utils.js
styles/colors.css
styles/styles.css
templates/article/article.css

Fix https://github.com/aemsites/cmegroup/issues/48
Fix https://github.com/aemsites/cmegroup/issues/49
Fix https://github.com/aemsites/cmegroup/issues/50
Test URLs:
- Before: https://main--cmegroup--aemsites.aem.page/drafts/anuj/education/articles-and-reports/case-study-a-regional-bank-plans-for-a-post-libor-world
- After: https://issue-48--cmegroup--aemsites.aem.page/drafts/anuj/education/articles-and-reports/case-study-a-regional-bank-plans-for-a-post-libor-world

fix: update styling for blocks in article page

---

blocks/header/header.css
blocks/hero/hero.css
blocks/hero/hero.js
styles/styles.css

Fix #65 
Test URLs:
- Before: https://main--cmegroup--aemsites.aem.live/drafts/anuj/education/articles-and-reports/copy-of-container-freight-rate-futures-frequently-asked-questions
- After: https://issue-65--cmegroup--aemsites.aem.live/drafts/anuj/education/articles-and-reports/copy-of-container-freight-rate-futures-frequently-asked-questions

Implementing new hero variant for Article FAQ Page

---

aemedge/scripts/taxonomy.js
aemedge/scripts/utils.js
tools/sidekick/library.html

Test URLs:
- Before: https://main--cmegroup--aemsites.aem.live/
- After: https://<branch>--cmegroup--aemsites.aem.live/

Quick fix: config folder moved to eds-config

---

aemedge/blocks/tags-cloud/tags-cloud.css
aemedge/blocks/tags-cloud/tags-cloud.js
aemedge/scripts/utils.js

Fix #88 
Test URLs:
- Before: https://main--cmegroup--aemsites.aem.live/drafts/nestor/tags
- After: https://issue-88-tags-cloud--cmegroup--aemsites.aem.live/drafts/nestor/tags

Issue 88 tags cloud

---

tools/sidekick/library/plugins/tags/tags.css
tools/sidekick/library/plugins/tags/tags.js

Fix the issue of search on tagger tool
Test URLs:
- Before: https://main--cmegroup--aemsites.aem.page/tools/sidekick/library.html?plugin=tags
- After: https://quick-fix-tagger-tool-search--cmegroup--aemsites.aem.page/tools/sidekick/library.html?plugin=tags

Quick fix for search on tagger tool

---

aemedge/blocks/columns/columns.css

Fix #87 
Test URLs:
- Before: https://main--cmegroup--aemsites.aem.page/drafts/nestor/article1
- After: https://issue-87-author-block--cmegroup--aemsites.aem.page/drafts/nestor/article1

Issue 87 author block

---

aemedge/blocks/form/form-fields.js
aemedge/blocks/form/form.js

Feedback form: Smiley icon path
Contact Us Form: Submit fragment path can be complete url or simple path
Test URLs:
- Before: https://main--cmegroup--aemsites.aem.live/education
- After: https://forms--cmegroup--aemsites.aem.live/education

smiley icon path and submit fragment path

---

aemedge/blocks/dynamic/tabs/tabs.js

Test URLs:
- Before: https://main--cmegroup--aemsites.aem.live/drafts/anuj/tabs
- After: https://tabs--cmegroup--aemsites.aem.live/drafts/anuj/tabs

fix: tabs minor bugs

---

aemedge/scripts/modules/Authentication.js

Test URLs:
- Before: https://main--cmegroup--aemsites.aem.live/drafts/ramiro/accordion
- After: https://beta-mapping-login-url--cmegroup--aemsites.aem.live/drafts/ramiro/accordion

beta-mapping-login-url

---

aemedge/scripts/utils.js

Test URLs:
- Before: https://main--cmegroup--aemsites.aem.live/
- After: https://<branch>--cmegroup--aemsites.aem.live/

Fixed getEnvType URLs

---

aemedge/blocks/iframe/iframe.css
aemedge/blocks/iframe/iframe.js

Render iframes given an href using its src.
Restrict iframe hosts to an allowlist managed in code.
Validate height.
Warn authors in preview when issue found
Fix #114 
Test URLs:
Before: https://main--www--cmegroup.aem.page/drafts/john/issue114-iframes-block
After:  https://issue114-iframe--www--cmegroup.aem.page/drafts/john/issue114-iframes-block
Block sidekick page
https://da.live/edit#/cmegroup/www/eds-config/sidekick/blocks/iframe

Issue 114 - Iframe support

---

aemedge/blocks/header/search/search.js

Test URLs:
- After: https://ad-nav-issues--www--cmegroup.aem.live/education

ad-nav-issues search in nav bugs fix

---

aemedge/scripts/alerts/alerts.js
aemedge/scripts/utils.js
aemedge/styles/styles.css

Test URLs:
- Before: https://main--wwww--cmegroup.aem.live/
- After: https://<branch>--www--cmegroup.aem.live/

Issue 105: alerts issues fixed

---

aemedge/blocks/header/header.css
aemedge/blocks/header/header.js

Fix: [Issue 178](https://github.com/aemsites/cmegroup/issues/178)
Test URLs:
- Before: https://main--www--cmegroup.aem.page/drafts/gperticarari/blank
- After: https://issue-178-subnav--www--cmegroup.aem.page/drafts/gperticarari/blank
The Navbar styles have been changed following the ones we have on our Prod environment.
Also, the columns were fixed.

Issue 178 subnav

---

aemedge/blocks/header/header.css
aemedge/scripts/alerts/alerts.js

Fix CUEN-201 navbar not moving when scroll
Test URLs:
- After: https://CUEN-201--www--cmegroup.aem.live/education

CUEN-201 navbar not moving when scroll

---

aemedge/blocks/header/header.css
aemedge/blocks/header/header.js

CUEN-62 external link in navbar fix
Test URLs:
- After: https://CUEN-62--www--cmegroup.aem.live/education

CUEN-62 external link in navbar fix

---

aemedge/blocks/header/header.css
aemedge/blocks/header/header.js

CUEN-159 update validation for logo without link in navbar
CUEN-159 nav margins fix for responsive use
Test URLs:
- After: https://CUEN-159--www--cmegroup.aem.live/education

Cuen 159 - nav margins fix for responsive use

---

aemedge/blocks/header/header.js

CUEN-61 close navbar after click on item
Test URLs:
- After: https://CUEN-61--www--cmegroup.aem.live/education

CUEN-61 close navbar after click on item

---

aemedge/blocks/header/header.css

login items in mobile navbar update margins
Test URLs:
- After: https://CUEN-157--www--cmegroup.aem.live/education

CUEN-157 login items in mobile navbar update margins

---

aemedge/blocks/table/table.css

Test URLs:
- Before: https://main--www--cmegroup.aem.live/drafts/nawaz/table
- After: https://issue-152--www--cmegroup.aem.live/drafts/nawaz/table

fix: allow option to disable row banding on tables block

---

aemedge/styles/styles.css

Added a padding top for main section on the global style file. This fixes the issue of the 404 page and also adds the correct padding for the rest of the site. Also made some small changes on some css rules that where not working.
Fix #198 
Test URLs:
- Before: https://main--www--cmegroup.aem.live/drafts/ssuarez/test
- After: https://issue-198-sorrypage--www--cmegroup.aem.live/drafts/ssuarez/test

Missing padding top on main style file

---

aemedge/blocks/table/table.css

Test URLs:
- Before: https://main--www--cmegroup.aem.live/drafts/nawaz/table
- After: https://table-hover-issue--www--cmegroup.aem.live/drafts/nawaz/table

fix: hover issue with table block

---

aemedge/blocks/cards/cards.js

ad-cards-fix cards query index point filter funtion fix after AD migration
Test URLs:
- After: https://ad-cards-fix--www--cmegroup.aem.live/education

ad-cards-fix cards query index point filter funtion fix after AD migr

---

aemedge/blocks/cards/cards-list-thumbnail-medium.css
aemedge/blocks/cards/cards.css
aemedge/blocks/cards/cards.js
aemedge/scripts/utils.js
aemedge/styles/colors.css
aemedge/templates/event/mock/event-template.html

Added a new variation for cards block to show 3 articled pulled from on prem AEM and show them as cards in desktop and as list in mobile
Fix #136 
Test URLs:
- Before: https://main--www--cmegroup.aem.page/drafts/nestor/event-copy
- After: https://issue-136-recommended-for-you-card-variation--www--cmegroup.aem.page/drafts/nestor/event-copy

Issue 136: Create recommended for you card variation

---

aemedge/scripts/popups/popups.js

Test URLs:
- After: https://issue-106-sitewide-popups-link-issue--www--cmegroup.aem.live/

Issue 106: fixed button link props

---

404.html

Fixed wrong paddings and margins on 404 page, “What’s Next”, “Useful Links” and the bottom padding with the footer.
Fix #199 
Test URLs:
- Before: https://main--www--cmegroup.aem.live/notfound
- After: https://issue-199-404margins--www--cmegroup.aem.live/notfound

fixed wrong paddings and margins on 404 page

---

aemedge/scripts/course/course.js

Test URLs:
- Before: https://main--www--cmegroup.aem.live/education/courses/mi-primer-curso/mi-primer-lesson
- After: https://courses-fix--www--cmegroup.aem.live/education/courses/mi-primer-curso/mi-primer-lesson

coursed fix

---

aemedge/blocks/quiz/quiz.css
aemedge/blocks/quiz/quiz.js
aemedge/styles/colors.css

Added quiz block. Once progress tracking has been defined with the backend, it needs to be updated to incorporate the progress.
Test URLs:
- Before: https://main--www--cmegroup.aem.page/drafts/joaco/quiz
- After: https://issue-25-quiz--www--cmegroup.aem.page/drafts/joaco/quiz

Issue 25: added quiz block

---

aemedge/scripts/utils/fetch.js

Test URLs:
- After: https://remove-is-protected-url--www--cmegroup.aem.live/education

remove isProtected param in api get/post - CORS fix

---

aemedge/scripts/course/course.js

Fix
Test URLs:
- Before: https://main--www--cmegroup.aem.page/drafts/daiana/education/courses/course-chapter/chapter1-copy/lesson-chapter2
- After: https://temp-fix--www--cmegroup.aem.page/drafts/daiana/education/courses/course-chapter/chapter1-copy/lesson-chapter2

Courses lesson fix for chapters

---

aemedge/blocks/cards/cards.js
aemedge/scripts/utils.js

Test URLs:
Before: https://main--www--cmegroup.aem.page/drafts/gperticarari/cards
After: https://cards-article-date-issue--www--cmegroup.aem.page/drafts/gperticarari/cards
The article date did not match the one on the Cards (article variation) component.

cards article issue with date fix

---

aemedge/blocks/quiz/quiz.css
aemedge/templates/lesson/lesson.css
aemedge/templates/lesson/lesson.js

Lateral navigation for the lesson template
Fix #118
Test URLs:
- Before: https://main--www--cmegroup.aem.live/drafts/daiana/education/courses/course-test
- After: https://issue-118-lesson-prev-next-navigation--www--cmegroup.aem.live/drafts/daiana/education/courses/course-test

Issue 118: added lateral navigation for the lesson template

---

aemedge/scripts/course/course.js

Fix 
Test URLs:
- Before: https://main--www--cmegroup.aem.page/drafts/piyush/education/courses/course-chapter/chapter1/lesson-chapter
- After: https://cl-cache-remove--www--cmegroup.aem.page/drafts/piyush/education/courses/course-chapter/chapter1/lesson-chapter

Setting cache time 0 for courses/lessons

---

aemedge/scripts/modules/Authentication.js

Test URLs:
- Before: https://main--www--cmegroup.aem.page/drafts/gperticarari/article
- After: https://register-redirection--www--cmegroup.aem.page/drafts/gperticarari/blank
The user should not be able to register from a non-production environment.

RegisterUrl change

---

aemedge/blocks/dynamic/course-nav/course-nav.js

Fix #274 
Test URLs:
- Before: https://main--www--cmegroup.aem.live/drafts/daiana/education/courses/course-chapter/lesson-chapter
- After: https://lesson-text--www--cmegroup.aem.live/drafts/daiana/education/courses/course-chapter/lesson-chapter

Lessons count in sidenav fixed

---

aemedge/blocks/header/header.css

Test URLs:
- Before: https://main--www--cmegroup.aem.page/drafts/gperticarari/blank
- After: https://nav-issues--www--cmegroup.aem.page/drafts/gperticarari/blank
Fixes:
Nav menu columns width on 1000px resolution was not showing properly.
Navbar icons not showing properly on mobile version.

nav columns issue and icons alignment on mobile

---

aemedge/blocks/event-calendar/event-calendar.css
aemedge/blocks/event-calendar/event-calendar.js

datepicker fixs
CUEN-236 datepicker position
CUEN-235 select two lines
CUEN-232 readonly date input
CUEN-231 datepicker calendar width
Test URLs:
- After: https://datepicker-fixs--www--cmegroup.aem.live/drafts/ramiro/event-calendar

Datepicker fixs

---

aemedge/blocks/dynamic/course-nav/course-nav.css
aemedge/templates/course/course-base.css

Fix #266 
Test URLs:
- Before: https://main--www--cmegroup.aem.live/education/courses/understanding-micro-futures-contracts-at-cme-group
- After: https://issue-266--www--cmegroup.aem.live/education/courses/understanding-micro-futures-contracts-at-cme-group

fix: course nav style fixes

---

aemedge/blocks/event-calendar/event-calendar.css
aemedge/blocks/event-calendar/event-calendar.js

CUEN-242 pills filter expand button fix
CUEN-234 event-calendar dropdowns placeholder fix
Test URLs:
- After: https://event-calendar-fixs--www--cmegroup.aem.live/drafts/ramiro/event-calendar

Event calendar fixs

---

aemedge/blocks/header/header.css

Added scroll behavior to the navbar when its height exceeds the viewport, ensuring all items remain accessible regardless of screen resolution or browser zoom. Also added bottom padding as requested by QA, as the navbar content was not displaying as expected.
Fix #211 
Test URLs:
- Before: https://main--www--cmegroup.aem.live/drafts/gperticarari/blank
- After: https://issue-199-navbarscroll--www--cmegroup.aem.live/drafts/gperticarari/blank

added scroll when navbar exceeds height

---

aemedge/blocks/cards/cards-list-thumbnail-medium.css
aemedge/blocks/hero/hero-event.css
aemedge/styles/styles.css

[CUEN-167 event feed page economic calendar btn overlap fix]
[CUEN-166 event feed pages styles differences fix]
[CUEN-221 recommended for you cards text padding fix]
[CUEN-220 recommended for you card text ellipsis fix]
Test URLs:
- After: https://econoday-event-fixes--www--cmegroup.aem.live/education/events/econoday/640178

Econoday event fixes

---

.eslintrc.js
aemedge/blocks/brightcove/brightcove.css
aemedge/blocks/brightcove/brightcove.js

brightcove video fixes
Test URLs:
- After: https://video-fixes--www--cmegroup.aem.live/drafts/ramiro/embed

video-fixes

---

aemedge/blocks/footer/footer.css

Fix https://github.com/aemsites/cmegroup/issues/330
Test URLs:
- Before: https://main--www--cmegroup.aem.page/drafts/gperticarari/blank
- After: https://issue-330-horizontal-scroll--www--cmegroup.aem.page/drafts/gperticarari/blank

issue-330 footer dropdown was causing the issue

---

aemedge/styles/styles.css

Fix [109](https://github.com/aemsites/cmegroup/issues/109)
Test URLs:
- Before: https://main--www--cmegroup.aem.page/drafts/gperticarari/icon-link
- After: https://issue-109--www--cmegroup.aem.page/drafts/gperticarari/icon-link
Icon color inside anchor

Icon color inside anchor

---

aemedge/blocks/cards/cards-blue-box.css

CUEN-271
link color in blue box cards
Test URLs:
- Before: https://main--www--cmegroup.aem.live/drafts/ramiro/cards
- After: https://issues-card-blue-box--www--cmegroup.aem.live/drafts/ramiro/cards

minor css card blue box link fix

---

aemedge/blocks/brightcove/brightcove.css
aemedge/blocks/brightcove/brightcove.js
aemedge/scripts/utils/gtm.js
aemedge/scripts/utils/index.js

Add dataLayer tracking events for video component
Test URLs:
- Before: https://main--www--cmegroup.aem.live/drafts/ramiro/embed
- After: https://issue-video-datalayer--www--cmegroup.aem.live/drafts/ramiro/embed

Issue video datalayer

---

aemedge/blocks/cards/cards-default.css
aemedge/blocks/cards/cards-upcoming-events.css
aemedge/blocks/cards/cards.js

Fix #342 
Test URLs:
- Before: https://main--www--cmegroup.aem.page/drafts/nestor/testing
- After: https://issue-342-bugfixing-in-cards--www--cmegroup.aem.page/drafts/nestor/testing

Issue 342 bugfixing in cards

---

aemedge/scripts/course/course.js
aemedge/templates/lesson-standalone/lesson-standalone.js

Fix #201 
Test URLs:
- Before: https://main--www--cmegroup.aem.live/drafts/daiana/education/courses/standalone
- After: https://issue-201-standalone-lesson-fixes--www--cmegroup.aem.page/drafts/daiana/education/courses/standalone

Issue 201 bugfixing in standalone lessons

---

aemedge/blocks/dynamic/course-nav/course-nav.css
aemedge/blocks/dynamic/course-nav/course-nav.js
aemedge/scripts/course/course.js
aemedge/templates/course/course.js

Apart from the main sorting issue, added changes for -
- aligning chapter title in course nav block to left
- Begin course button was not appearing properly for few courses.
Fix #259 
Test URLs:
- Before: https://main--www--cmegroup.aem.live/drafts/anuj/education/courses/introduction-to-agriculture
- After: https://issue-259--www--cmegroup.aem.live/drafts/anuj/education/courses/introduction-to-agriculture

fixed modulesOrder for lesson and chapter at same hierarchy

---

aemedge/blocks/event-calendar/event-calendar.css

minor css fixes in event calendar table
Test URLs:
- Before: https://main--www--cmegroup.aem.live/drafts/ramiro/event-calendar
- After: https://calendar-css-fixs--www--cmegroup.aem.live/drafts/ramiro/event-calendar

calendar-css-fixs table margins

---

aemedge/blocks/cards/cards-promo-link.css

Fix [384](https://github.com/aemsites/cmegroup/issues/384)
Test URLs:
- Before: https://main--www--cmegroup.aem.page/drafts/gperticarari/cards
- After: https://issue-384-cards--www--cmegroup.aem.page/drafts/gperticarari/cards
promo-link cards arrow positioning fix

promo-link cards arrow positioning fix

---

aemedge/scripts/course/course.js
aemedge/scripts/services/EducationTrackService.js
aemedge/templates/lesson-standalone/lesson-standalone.js
aemedge/templates/lesson/lesson.js

Fix #201 
Test URLs:
Before: https://main--www--cmegroup.aem.page/drafts/daiana/education/courses/standalone
After: https://issue-201-lesson-status-fixes--www--cmegroup.aem.page/drafts/daiana/education/courses/standalone

Issue 201 bugfixing for lessons progress status

---

aemedge/blocks/dynamic/course-nav/course-nav.css
aemedge/blocks/dynamic/course-nav/course-nav.js
aemedge/scripts/course/course.js
aemedge/templates/course/course-base.css
aemedge/templates/course/course.css
aemedge/templates/course/course.js

Also fixed other related styling issues -
1. Course nav width handling for different views
2. Course nav top position when alert is present
3. Read Time header gap b/w icon and text
Fix https://github.com/aemsites/cmegroup/issues/357 https://github.com/aemsites/cmegroup/issues/359 https://github.com/aemsites/cmegroup/issues/360 #371 
Test URLs:
- Before: 
https://main--www--cmegroup.aem.live/education/courses/basic-principles-of-micro-wti-crude-oil-futures/option-hedging-with-micro-wti-crude-oil-futures
https://main--www--cmegroup.aem.live/education/courses/basic-principles-of-micro-wti-crude-oil-futures/option-hedging-with-micro-wti-crude-oil-futures
https://main--www--cmegroup.aem.live/education/courses/cme-institute-live
- After: …

course styling issues

---

aemedge/blocks/search/search.css
aemedge/blocks/search/sort/sort.css

Fix 
Test URLs:
- Before: https://main--www--cmegroup.aem.live/drafts/piyush/temp-search-copy
- After: https://mobile-view-fix--www--cmegroup.aem.live/drafts/piyush/temp-search-copy

Search Mobile view fixes

---

aemedge/scripts/course/course.js

Fix #379 
Test URLs:
- Before: https://main--www--cmegroup.aem.live/education/courses/building-a-trade-plan
- After: https://issue-379--www--cmegroup.aem.live/education/courses/building-a-trade-plan

fixing course base path for beta environment

---

aemedge/scripts/course/course.js

Fix #379 
Test URLs:
- After: https://issue-379--www--cmegroup.aem.live/

Course base path handling for beta site

---

aemedge/blocks/columns/columns.css
aemedge/blocks/hero/hero-event.css
aemedge/blocks/hero/hero.css
aemedge/blocks/hero/hero.js
aemedge/styles/colors.css
aemedge/styles/styles.css
aemedge/templates/event/event.css

Added new event template and the required variations:
- New template page structure
- New hero variation
- New section divider style
- New column variation to allow building text + link on the right
Fix #311 
Test URLs:
- Before: https://main--www--cmegroup.aem.page/education/2025/commodity-index-trading-webinar
- After: https://issue-311-event-template--www--cmegroup.aem.page/education/2025/commodity-index-trading-webinar

Issue 311 event template

---

aemedge/blocks/modal/modal.js

Fix : #404
Fix scroll jump behavior for modals
Test URLs:
- After: https://issue-scrollfix--www--cmegroup.aem.page/drafts/john/issue146-image-lightbox
- After: https://issue-scrollfix--www--cmegroup.aem.page/education/events/econoday/636612

Fix scroll jump behavior for modals

---

aemedge/blocks/table/table.css
aemedge/styles/styles.css

Test URLs:
- Before: https://main--www--cmegroup.aem.live/drafts/nawaz/data-table
- After: https://data-table--www--cmegroup.aem.live/drafts/nawaz/data-table

fix: support data table

---

aemedge/blocks/columns/columns.css

education-layout-columns
Test URLs:
- After: https://issue-education-layout-columns--www--cmegroup.aem.live/drafts/ramiro/

issue-education-layout-columns add 75-25 option

---

aemedge/scripts/aem.js
aemedge/scripts/scripts.js

personalization spike - add customId to blocks
(event component has id="newCustomId")
Test URLs:
- Before: https://main--www--cmegroup.aem.live/drafts/ramiro/event-calendar
- After: https://issue-285-personalization-spike--www--cmegroup.aem.live/drafts/ramiro/event-calendar

personalization spike - add customId to blocks

---

aemedge/scripts/course/auth-modal.js
aemedge/scripts/course/certificate.js
aemedge/scripts/services/EducationTrackService.js
aemedge/templates/course/course-base.css
aemedge/templates/lesson-standalone/lesson-standalone.js
aemedge/templates/lesson/lesson.js

Education - courses auth .prompt
If a user is not logged in, user is prompted to log in or registration.
Fix https://github.com/aemsites/cmegroup/issues/203
Test URLs:
Before: https://main--www--cmegroup.aem.live/drafts/daiana/education/courses/course-chapter/chapter1/lesson-chapter
After: https://issue-203-education-auth-prompt--www--cmegroup.aem.live/drafts/daiana/education/courses/course-chapter/chapter1/lesson-chapter

Issue 203 - Course/Lessons auth prompt

---

aemedge/blocks/columns/columns.css

landing layout 75 / 25
Test URLs:
- Before: https://main--www--cmegroup.aem.live/drafts/ramiro/
- After: https://issue-landing-layout--www--cmegroup.aem.live/drafts/ramiro/

issue-landing-layout

---

aemedge/templates/econoday-event/mock/event-template.html

Fix #431 
Test URLs:
- After: https://<branch>--www--cmegroup.aem.live/

Issue 431: Econoday page table style

---

aemedge/blocks/event-list/event-list.js

Fix #442 
Test URLs:
- Before: https://main--www--cmegroup.aem.live/drafts/nestor/calendar
- After: https://issue-442-event-list-safari-issue--www--cmegroup.aem.live/drafts/nestor/calendar

Issue-442: Event List block issue on safari

---

aemedge/styles/styles.css

education landing smooth scroll
Test URLs:
- After: https://issue-landing-smooth-scroll--www--cmegroup.aem.live/education

education landing smooth scroll

---

aemedge/blocks/event-list/event-list.css

Event list mobile padding fix
Fix #449 
Test URLs:
- Before: https://main--www--cmegroup.aem.page/drafts/nestor/calendar
- After: https://issue-449-event-list-mobile-padding-fix--www--cmegroup.aem.page/drafts/nestor/calendar

Issue-449: Event list mobile padding fix

---

aemedge/blocks/footer/footer.js
aemedge/blocks/header/header.js
aemedge/scripts/aem.js
aemedge/scripts/scripts.js

- Fixed accessibility issues in Header/Footer
- Adjusted the decorateIcons() method to auto-apply accessibility for icon links 
Note : Accessibility is not 100 coz we have contrast issue with color scheme being used in CME site. This can be look later after golive and can involve design team in the future to make it to 100
Fix #301 
Test URLs:
- Before: https://main--www--cmegroup.aem.page/drafts/kunwar/agriculture-cash-settlement-vs-physical-delivery
- After: https://issue-301-accessbility-headerfooter--www--cmegroup.aem.page/drafts/kunwar/agriculture-cash-settlement-vs-physical-delivery

Acccessibility issues for Header/Footer

---

aemedge/styles/styles.css

external link hover animation
Test URLs:
- After: https://issue-external-link-hover--www--cmegroup.aem.live/education

external link hover animation

---

aemedge/blocks/cards/cards-related-courses.css
aemedge/templates/course/course.css

Fix #266 
Test URLs:
- Before: https://main--www--cmegroup.aem.live/education/courses/cme-institute-live
- After: https://issue-266-1--www--cmegroup.aem.live/education/courses/cme-institute-live

fix: begin course button

---

aemedge/scripts/indexing.js

Search API quickfix tags
Test URLs:
- Before: https://main--www--cmegroup.aem.live/drafts/chamo/new-cards
- After: https://search-api-quickfix-tags--www--cmegroup.aem.live/drafts/chamo/new-cards

Search API quickfix tags

---

aemedge/blocks/dynamic/course-nav/course-nav.css
aemedge/scripts/scripts.js
aemedge/styles/styles.css

Fix# 474 Empty space on header when hidden
Before: https://main--www--cmegroup.aem.live/drafts/daiana/education/courses/course-share?hideHeader=y
After: https://issue-474-headerSpace--www--cmegroup.aem.live/drafts/daiana/education/courses/course-share?hideHeader=y
Add a class for hidden and override styles to remove space

Fix# 474 Empty space on header when hidden

---

aemedge/blocks/brightcove/brightcove.js
aemedge/blocks/tags-cloud/tags-cloud.js
tools/importer/importer.js

Fix : #502 
Test URLs:
- Before: https://main--www--cmegroup.aem.live/education/videos/us-policy-responses-to-economic-distress
- After: https://new-changes--www--cmegroup.aem.live/education/videos/us-policy-responses-to-economic-distress

Video and tag bug fix & importer changes

---

aemedge/blocks/hero/hero-base.css
aemedge/blocks/hero/hero-landing.css
aemedge/blocks/hero/hero.js

Refactor of hero landing css file. Added "small" variation to be combined with leadspace.
Fix #208 
Test URLs:
- Before: https://main--www--cmegroup.aem.page/drafts/nestor/landing
- After: https://issue-208-course-catalog-hero--www--cmegroup.aem.page/drafts/nestor/landing

Issue 208 course catalog hero

---

aemedge/scripts/course/course.js
aemedge/templates/course/course-base.css

Premium label for lessons
Test URLs:
- Before: https://main--www--cmegroup.aem.live/education/courses/cme-institute-live/chapter-1-introduction-to-cme-group-and-fundamentals-of-financial-futures-and-options/introduction-to-cme-group
- After: https://issue-cuwdi-13-premiun-lesson--www--cmegroup.aem.live/education/courses/cme-institute-live/chapter-1-introduction-to-cme-group-and-fundamentals-of-financial-futures-and-options/introduction-to-cme-group

premium label for lessons

---

aemedge/scripts/services/EducationTrackService.js

Fixing issue saving education local storage tracking after login
Fix https://github.com/aemsites/cmegroup/issues/201 - Course Progress Tracking
Test URLs:
Before: https://main--www--cmegroup.aem.page/drafts/daiana/education/courses/course-chapter/chapter1/lesson-chapter-1
After: https://issue-education-tracking-storage--www--cmegroup.aem.page/drafts/daiana/education/courses/course-chapter/chapter1/lesson-chapter-1

Issue 283: issue storing local storage tracking after login

---

aemedge/blocks/course-progress/course-progress.js

Backend services updates for Course Progress Bar.
Fix https://github.com/aemsites/cmegroup/issues/205
Test URLs:
Before: https://main--www--cmegroup.aem.page/drafts/mariano/education
After: https://course-progress-service-update--www--cmegroup.aem.page/drafts/mariano/education

Issue 205: Course Progress - backend services updates

---

.env.json
aemedge/templates/course/course-base.css
aemedge/templates/lesson/lesson.js

Fix #503 
Test URLs:
- Before: https://main--www--cmegroup.aem.live/education/courses/understanding-stir-futures/trading-sonia-futures
- After: https://503--www--cmegroup.aem.live/education/courses/understanding-stir-futures/trading-sonia-futures

fix: lateral navigation position

---

aemedge/scripts/course/certificate.js
aemedge/scripts/course/course.js
aemedge/scripts/indexing.js
aemedge/scripts/legacy-api.js
aemedge/scripts/services/AuthenticationService.js
aemedge/scripts/services/EconomicReleaseService.js
aemedge/scripts/services/EducationTrackService.js
aemedge/scripts/services/SearchResultsService.js
aemedge/scripts/utils.js
aemedge/scripts/utils/env.js
aemedge/scripts/utils/index.js
aemedge/templates/article/article.js

Article link to author bio
Fix #535
Test URLs:
- Before: https://main--www--cmegroup.aem.live/drafts/ramiro/10-reasons-to-consider-managed-futures
- After: https://article-link-to-bio-380--www--cmegroup.aem.live/drafts/ramiro/10-reasons-to-consider-managed-futures

Article link to bio 380

---

aemedge/blocks/search/search-results/search-results.css
tools/importer/course-lesson.js
tools/importer/importer.js
tools/importer/utils.js

Fix
Test URLs:
- After: https://import-feedback--www--cmegroup.aem.live/

Importer feedback and bug fix in search ui

---

aemedge/blocks/dynamic/course-nav/course-nav.js
aemedge/blocks/dynamic/index.js
aemedge/scripts/scripts.js
aemedge/scripts/utils.js
aemedge/templates/lesson/lesson.js

Hide Blocks/Fragments based on query params or if the page is in Iframe
Fix https://github.com/aemsites/cmegroup/issues/405
Test URLs:
Before: https://main--www--cmegroup.aem.page/education
After: https://issue-405-hide-blocks-education-params--www--cmegroup.aem.page/education

Issue 405: hide blocks based on query params

---

aemedge/blocks/cards/cards-article.css

filter update for play icon in cards
Fix #194 
Test URLs:
- Before: https://main--www--cmegroup.aem.live/drafts/ramiro/fragment-extend
- After: https://issue-card-play-icon--www--cmegroup.aem.live/drafts/ramiro/fragment-extend

issue-card-play-icon filter update

---

aemedge/templates/article/article.css

articles css fixes
Fix #551, #549, #543, #544
Test URLs:
- Before: https://main--www--cmegroup.aem.live/drafts/ramiro/10-reasons-to-consider-managed-futures
- After: https://issue-articles-CUEN-407--www--cmegroup.aem.live/drafts/ramiro/10-reasons-to-consider-managed-futures
- Before: https://main--www--cmegroup.aem.live/drafts/ramiro/nowcasting-the-us-economy-with-alternative-data
- After: https://issue-articles-CUEN-407--www--cmegroup.aem.live/drafts/ramiro/nowcasting-the-us-economy-with-alternative-data

articles css fixes

---

aemedge/templates/article/article.css

article authors width css fix
Test URLs:
- Before: https://main--www--cmegroup.aem.live/drafts/ramiro/10-reasons-to-consider-managed-futures
- After: https://article-400--www--cmegroup.aem.live/drafts/ramiro/10-reasons-to-consider-managed-futures

article authors width css fix

---

aemedge/blocks/cards/cards-white-raised-box.css

update white raise card css to setion full width layout
Test URLs:
- Before: https://main--www--cmegroup.aem.live/drafts/ramiro/courses/option-hedging-with-micro-wti-crude-oil-futures
- After: https://card-white-raise-fix--www--cmegroup.aem.live/drafts/ramiro/courses/option-hedging-with-micro-wti-crude-oil-futures

update white raise card css to setion full width layout

---

aemedge/blocks/form/form-contact-us.css
aemedge/blocks/form/form.js

Contact Us Form - improvements/fixes
Fix https://github.com/aemsites/cmegroup/issues/71
Test URLs:
Before: https://main--www--cmegroup.aem.page/education
After: https://contact-us-form-fixes--www--cmegroup.aem.page/education

Contact us form fixes

---

aemedge/templates/lesson/lesson.js

- Placing the fragment on template level to cover for #503 
Fix #503 
Test URLs:
- Before: https://main--www--cmegroup.aem.page/education/courses/basic-principles-of-micro-wti-crude-oil-futures/basic-principles-of-micro-crude-oil-options
- After: https://lesson-template--www--cmegroup.aem.page/education/courses/basic-principles-of-micro-wti-crude-oil-futures/basic-principles-of-micro-crude-oil-options

Placing the fragment on template level to cover for #503 

---

aemedge/blocks/dynamic/course-nav/course-nav.css

Fix #575 
Test URLs:
- Before: https://main--www--cmegroup.aem.live/education/courses/clearing/what-is-clearing
- After: https://issue575-coursenav-align--www--cmegroup.aem.live/education/courses/clearing/what-is-clearing

Course-nav aligned to course-header

---

aemedge/blocks/hero/hero-landing.css

Arrow color issue
Fix #583 
Test URLs:
- Before: https://main--www--cmegroup.aem.page/drafts/ivang/test-webpages/hero-block-variant-2
- After: https://issue-583-hero-arrow-color-issue--www--cmegroup.aem.page/drafts/ivang/test-webpages/hero-block-variant-2

Issue-583: Course catalog hero block arrow color issue

---

aemedge/blocks/divider/divider.css
tools/sidekick/jump-links/README.md
tools/sidekick/jump-links/jump-links.css
tools/sidekick/jump-links/jump-links.html
tools/sidekick/jump-links/jump-links.js

- DA plugin for jump links
- Added a divider block
See screencast for this : https://www.loom.com/share/a67494080d0a443baf8c3e3b2a95c135?sid=917c67a4-fb09-4f92-94ed-ce2f937fe415
Fix #561 , #165 
Test URLs:
- Before: https://main--www--cmegroup.aem.live/drafts/kunwar/topix-futures-frequently-asked-questions
- After: https://jumpoff-links--www--cmegroup.aem.live/drafts/kunwar/topix-futures-frequently-asked-questions

Jumpoff links

---

aemedge/blocks/columns/columns-default.css

columns new options
Test URLs:
- Before: https://main--www--cmegroup.aem.live/drafts/ramiro/columns
- After: https://issue-column-options-410--www--cmegroup.aem.live/drafts/ramiro/columns

columns new options

---

aemedge/templates/course/course.js

Begin button is not displayed once course is completed
Fix https://github.com/aemsites/cmegroup/issues/187
Test URLs:
Before: https://main--www--cmegroup.aem.live/drafts/daiana/education/courses/course-chapter
After: https://courses-begin-button-issues--www--cmegroup.aem.live/drafts/daiana/education/courses/course-chapter

Begin button is not displayed once course is completed - CUWDI-120

---

tools/search.html
tools/search/search.css
tools/search/search.js

Fix 
Test URLs:
- After: https://findreplace-changes--www--cmegroup.aem.live/education

Findreplace changes

---

aemedge/blocks/table/table.css
aemedge/blocks/table/table.js

fixes for tables issues
Fix #589
Test URLs:
- Before: https://main--www--cmegroup.aem.live/education/articles-and-reports/3-year-treasury-note-futures-yield-curve-spreads
- After: https://issue-589-tables--www--cmegroup.aem.live/education/articles-and-reports/3-year-treasury-note-futures-yield-curve-spreads
- Before: https://main--www--cmegroup.aem.live/education/articles-and-reports/a-cost-comparison-of-russell-2000-futures-and-etfs
- After: https://issue-589-tables--www--cmegroup.aem.live/education/articles-and-reports/a-cost-comparison-of-russell-2000-futures-and-etfs
- Before: https://main--www--cmegroup.aem.live/education/articles-and-reports/a-cost-comparison-of-sp-500-related-options
- After: https://issue-589-tables--www--cmegroup.aem.live/education/articles-and-reports/a-cost-comp …

fixes for tables issues

---

tools/access-control/access-control.js

Avoid direct ims calls, cors errors
Test URLs:
- After: https://da-apps-permissions--www--cmegroup.aem.live/

DA custom apps | access control

---

aemedge/styles/styles.css

share this mobile position fix
Test URLs:
- After: https://sharethis-position-415--www--cmegroup.aem.live/education

share this mobile position fix

---

aemedge/blocks/divider/divider.css
aemedge/blocks/divider/divider.js

- supporting all faq style pages by using divider (back-to-top) variant
Fix #614 
Test URLs:
- Before: https://main--www--cmegroup.aem.page/drafts/kunwar/indigoag-faq
- After: https://issue-divider-backtotop--www--cmegroup.aem.page/drafts/kunwar/indigoag-faq

Divider (back-to-top)

---

aemedge/blocks/cta/cta.css

promobox cta new styles
Fix #617
Test URLs:
- Before: https://main--www--cmegroup.aem.live/education/articles-and-reports/basis-trade-at-index-close-btic-versatility
- After: https://issue-617-promobox--www--cmegroup.aem.live/education/articles-and-reports/basis-trade-at-index-close-btic-versatility
- Before: https://main--www--cmegroup.aem.live/education/articles-and-reports/case-study-a-regional-bank-plans-for-a-post-libor-world
- After: https://issue-617-promobox--www--cmegroup.aem.live/education/articles-and-reports/case-study-a-regional-bank-plans-for-a-post-libor-world
- Before: https://main--www--cmegroup.aem.live/education/articles-and-reports/case-study-hedging-new-crop-exposure-in-corn-before-march-usda
- After: https://issue-617-promobox--www--cmegroup.aem.live/education/article …

promobox cta new styles

---

aemedge/styles/styles.css

social bar index update
Test URLs:
- After: https://social-bar-index--www--cmegroup.aem.live/education

social bar index update

---

aemedge/styles/styles.css

sections - bg not full width
Fix #525
Test URLs:
- Before: https://main--www--cmegroup.aem.live/drafts/ramiro/hedging-with-wti-crude-oil-weekly-options
- After: https://issue-525--www--cmegroup.aem.live/drafts/ramiro/hedging-with-wti-crude-oil-weekly-options

sections - bg not full width

---

aemedge/scripts/services/SearchResultsService.js

remove search api key from repo
Test URLs:
- After: https://search-api-key--www--cmegroup.aem.live/

remove search api key from repo

---

aemedge/blocks/podcast/podcast.css
tools/importer/importer.js

Import pages with clickable images and convert these clickable images into cards (static, clickable-image) variant
Fix #643 
Test URLs:
- Before: https://main--www--cmegroup.aem.live/education/bitcoin/frequently-asked-questions
- After: https://issue643-import-clickableimages--www--cmegroup.aem.live/education/bitcoin/frequently-asked-questions

Issue643 import clickableimages

---

aemedge/blocks/hero/hero.css

Fix #639 
Test URLs:
- After: https://issue-639-2--www--cmegroup.aem.live/education

Issue-639: Second part

---

package.json

Adds lint fix scripts to automatically fix common linting issues.

feat: add lint fix scripts

---

aemedge/scripts/legacy-api.js
aemedge/scripts/modules/Authentication.js
aemedge/scripts/services/AuthenticationService.js
aemedge/scripts/utils/cookie.js
aemedge/scripts/utils/env.js

Updated login flow so that users can login from EDS pages.
Fix #651 
Test URLs:
- After: https://issue-651-login-update--www--cmegroup.aem.live/

feat(cuwst-439): login flow update

---

aemedge/blocks/cards/cards.js
aemedge/scripts/utils/dom.js

Fix #642
Test URLs:
- Before: https://main--www--cmegroup.aem.live/education/bitcoin/frequently-asked-questions
- After: https://clickable-cards--www--cmegroup.aem.live/education/bitcoin/frequently-asked-questions

feat: clickable cards

---

aemedge/blocks/dynamic/course-nav/course-nav.css

Fix [674](https://github.com/aemsites/cmegroup/issues/674)
Test URLs:
- Before: https://main--www--cmegroup.aem.page/drafts/daiana/education/courses/course-share
- After: https://issue-674-course-navbar--www--cmegroup.aem.page/drafts/daiana/education/courses/course-share

issue-674-course-navbar positioning when alerts are present fix

---

aemedge/scripts/delayed.js

Test URLs:
- Before: https://main--www--cmegroup.aem.page/drafts/nawaz/block-protection
- After: https://login-modal--www--cmegroup.aem.page/drafts/nawaz/block-protection

fix: metadata keyword for login popup

---

aemedge/scripts/course/course.js

Language Dropdown fixbug hide dropdown when only one link
Fix https://github.com/aemsites/cmegroup/issues/200
Test URLs:
Before: https://main--www--cmegroup.aem.live/education/courses/introduction-to-futures
After: https://language-dropdown-issue-one-link--www--cmegroup.aem.live/education/courses/introduction-to-futures

Issue 200: Language Dropdown fixbug hide dropdown when only one link

---

aemedge/blocks/add-to-calendar/add-to-calendar.css
aemedge/blocks/cards/cards-blue-box.css
aemedge/blocks/cards/cards-default.css
aemedge/blocks/cards/cards-full-width-gray.css
aemedge/blocks/cards/cards.js
aemedge/blocks/carousel/carousel.css
aemedge/blocks/columns/columns-default.css
aemedge/blocks/cta/cta.css
aemedge/blocks/cta/cta.js
aemedge/blocks/header/components/main.css
aemedge/blocks/hero/hero-landing.css
aemedge/blocks/jump-nav/jump-nav.css
aemedge/blocks/jump-nav/jump-nav.js
aemedge/blocks/table/table.css
aemedge/scripts/scripts.js
aemedge/styles/colors.css
aemedge/styles/styles.css

Fix #658
**Test URLs:**
**Before**
- [https://main--www--cmegroup.aem.page/education/academic-resources](https://main--www--cmegroup.aem.page/education/academic-resources)
- [https://main--www--cmegroup.aem.page/education/brochures-and-handbooks/the-complete-introducing-broker-handbook](https://main--www--cmegroup.aem.page/education/brochures-and-handbooks/the-complete-introducing-broker-handbook)
- [https://main--www--cmegroup.aem.page/education/courses/curriculum-all-about-options](https://main--www--cmegroup.aem.page/education/courses/curriculum-all-about-options)
- [https://main--www--cmegroup.aem.page/education/navigating-uncleared-margin-ru …

Design Polish

---

aemedge/blocks/brightcove-experience/brightcove-experience.css
aemedge/blocks/brightcove-experience/brightcove-experience.js
aemedge/blocks/dynamic/course-nav/course-nav.css

Brigthcove experience component
Fix #671
Test URLs:
- Before: https://main--www--cmegroup.aem.live/drafts/ramiro/bc-experience
- After: https://issue-671-bc-experience--www--cmegroup.aem.live/drafts/ramiro/bc-experience

Issue 671 bc experience

---

aemedge/blocks/dynamic/course-nav/course-nav.css

Fix [674](https://github.com/aemsites/cmegroup/issues/674)
Test URLs:
- Before: https://main--www--cmegroup.aem.page/drafts/daiana/education/courses/course-share
- After: https://issue-674-course-navbar--www--cmegroup.aem.page/drafts/daiana/education/courses/course-share

Issue 674 course navbar

---

aemedge/blocks/cards/cards-full-width-gray.css

card gray bg link color fix
Test URLs:
- After: https://card-bg-gray-links-fix--www--cmegroup.aem.live/education

card gray bg link color fix

---

aemedge/blocks/cards/cards-blue-box.css
aemedge/blocks/cards/cards-full-width-gray.css
aemedge/blocks/cards/cards-white.css
aemedge/blocks/cards/cards.css
aemedge/blocks/jump-nav/jump-nav.css
aemedge/blocks/language-selector/language-selector.css
aemedge/scripts/scripts.js
aemedge/styles/styles.css
aemedge/templates/course/course-base.css

landing pages fixes
Test URLs:
- Before: https://main--www--cmegroup.aem.live/education/navigating-uncleared-margin-rules
- After: https://landing-page-fixes--www--cmegroup.aem.live/education/navigating-uncleared-margin-rules

landing pages fixes

---

aemedge/blocks/course-progress/course-progress-delayed.js
aemedge/blocks/form/form.js
aemedge/blocks/header/header.js
aemedge/scripts/modules/Authentication.js
aemedge/scripts/modules/CookieBridge.js
aemedge/scripts/utils/cookie.js
aemedge/scripts/utils/fetch.js
aemedge/scripts/utils/misc.js
login-confirmed.html

This will allow login from aem.live and aem.page domains.
Test URLs:
- After: https://login-cross-env-svc--www--cmegroup.aem.live/

Cookie bridge connector for login/logout flows

---

aemedge/scripts/modules/Authentication.js

Updated auth links so that www content can hit nr auth environments. Prevent the execution of the cookie bridge when the origin is the target.
Test URLs:
- After: https://login-minor-fix--www--cmegroup.aem.live/

Login minor fix

---

aemedge/blocks/cards/cards-white-raised-box.css

white raise card new padding option
Test URLs:
- Before: https://main--www--cmegroup.aem.live/education/cme-direct
- After: https://white-raise-card-padding--www--cmegroup.aem.live/education/cme-direct

white raise card new padding option

---

aemedge/blocks/columns/columns-education.css
aemedge/blocks/hero/hero-landing.css

Landing more fixes
Test URLs:
- Before: https://main--www--cmegroup.aem.live/education/cme-direct
- After: https://landing-more-fixes--www--cmegroup.aem.live/education/cme-direct

Landing more fixes

---

aemedge/blocks/cards/cards-article-medium.css
aemedge/blocks/cards/cards.css
aemedge/blocks/cards/cards.js
aemedge/scripts/utils.js

Added "medium" cards block variant, with 2 variants:
1. medium, hide-time: hide the article time in the cards
2. medium, featured: makes the first card as a featured card (wider in desktop, with a background image and an overlay)
Fix #728 
Test URLs:
- Before: https://main--www--cmegroup.aem.page/drafts/nestor/cards
- After: https://issue-728-cards-article-medium--www--cmegroup.aem.page/drafts/nestor/cards

Issue 728 cards article medium

---

login-confirmed.html

Updating login iframe styles
Test URLs:
- After: https://login-iframe-fix--www--cmegroup.aem.live/

Login changes - login iframe styles fix

---

aemedge/blocks/course-progress/course-progress-delayed.js
aemedge/blocks/course-progress/course-progress.css

Course Progress Bar Styling issues
Fix https://github.com/aemsites/cmegroup/issues/205
Test URLs:
Before: https://main--www--cmegroup.aem.page/education
After: https://course-progress-fixes--www--cmegroup.aem.page/education

Issue 205: Course Progress Bar Styling issues - CUWDI-103

---

aemedge/blocks/table/table.css
aemedge/blocks/table/table.js

Test URLs:
- Before: https://main--www--cmegroup.aem.live/education/articles-and-reports/options-observer-wti-weekly-options-are-trending
- After: https://tablefix--www--cmegroup.aem.live/education/articles-and-reports/options-observer-wti-weekly-options-are-trending
- After: https://tablefix--www--cmegroup.aem.page/eds-config/sidekick/blocks/table

fix(table): handle rowspan in header rows for complex tables

---

aemedge/blocks/course-progress/course-progress-delayed.js

Course Progress Bar Api changes
Fix https://github.com/aemsites/cmegroup/issues/205
Test URLs:
Before: https://main--www--cmegroup.aem.page/education
After: https://course-progress-api-changes--www--cmegroup.aem.page/education

Issue 205: Course Progress Bar Api changes

---

aemedge/blocks/dynamic/index.js
aemedge/scripts/course/course.js
aemedge/templates/lesson/lesson.js

Prevent Course Nav loading if the hideCourseNav selector is present in an iframed course/lesson
Test URLs:
- After: https://ed-iframe-redirect--www--cmegroup.aem.live/

Prevent Course Nav loading if the hideCourseNav selector is present in an iframed course/lesson

---

aemedge/scripts/utils/env.js

Cards block is not working properly in preview block library
Fix #762 
Test URLs:
- Before: https://main--www--cmegroup.aem.page/drafts/nestor/iframed
- After: https://issue-762-preview-block-fix--www--cmegroup.aem.page/drafts/nestor/iframed

Issue-762: Preview block library cards fix

---

aemedge/blocks/brightcove/brightcove.js

Support video in yahoo rss feed
Fix #
Test URLs:
Before: https://main--www--cmegroup.aem.live/drafts/mariano/education/courses/basic-principles-of-micro-wti-crude-oil-futures/basic-principles-of-micro-crude-oil-options
After: https://brighcove-feed-video-url--www--cmegroup.aem.live/drafts/mariano/education/courses/basic-principles-of-micro-wti-crude-oil-futures/basic-principles-of-micro-crude-oil-options

Support video in yahoo rss feed

---

aemedge/blocks/brightcove/brightcove.css
aemedge/blocks/brightcove/brightcove.js

new brigthcove variation - fix multiple videos in page issue
Test URLs:
- Before: https://main--www--cmegroup.aem.live/drafts/ramiro/2videos
- After: https://video-playlist-horizontal--www--cmegroup.aem.live/drafts/ramiro/2videos

new brigthcove variation - fix multiple videos in page issue
