blocks/hero/hero.js
scripts/ffetch.js
scripts/taxonomy.js
scripts/utils.js
tools/sidekick/library.html
tools/sidekick/library/plugins/tags/tags.css
tools/sidekick/library/plugins/tags/tags.js
tools/sidekick/library/plugins/templates/templates.css
tools/sidekick/library/plugins/templates/templates.js

Upgrades the tags plugin according to the new structure of the taxonomy spreadsheet.
Updates the hero block to pull the primary topic and author labels from taxonomy file.
Fix #93 
Test URLs:
- Before: https://main--cmegroup--aemsites.aem.page/tools/sidekick/library.html
- After: https://issue-93-tagging-enhancements--cmegroup--aemsites.aem.page/tools/sidekick/library.html
Sample of article pulling labels for hero from taxonomy file:
https://issue-93-tagging-enhancements--cmegroup--aemsites.aem.page/drafts/nestor/article1
Taxonomy file:
https://docs.google.com/spreadsheets/d/1bLDh0Ldn11-vwZKTbiYx1-w0gKveMXMoo07IvUZI30o/edit?gid=864386553#gid=864386553

Issue 93 tagging enhancements

---

aemedge/styles/styles.css
aemedge/styles/util-styles-responsive.css
aemedge/styles/util-styles.css

Fix 92
https://github.com/aemsites/cmegroup/issues/92
Test URLs:
Before: [https://main--cmegroup--aemsites.aem.page/drafts/john/issue92-teststyles](https://main--cmegroup--aemsites.aem.page/drafts/john/issue92-teststyles)
After: [https://issue-92-globalUtilStyles--cmegroup--aemsites.aem.page/drafts/john/issue92-teststyles](https://issue-92-globalutilstyles--cmegroup--aemsites.aem.page/drafts/john/issue92-teststyles)
Split util styles into its own .css
Made a copy of them into corresponding -responsive.css Imported both into style.css

Issue 92 - Global Util Styles

---

aemedge/blocks/cards/cards.js
aemedge/blocks/faq/faq.js
aemedge/blocks/hero/hero-article.css
aemedge/blocks/hero/hero.js
aemedge/scripts/taxonomy.js
aemedge/scripts/utils.js

- Added the translations file in gdrive at /cmegroup/eds-config/translations
- Added i18n utility function in JS to get the translation for a text
- Updated blocks to use the translations: hero, cards, faq
Fix #24
Test URLs:
- Before: https://main--cmegroup--aemsites.aem.live/education
- After: https://issue-24-translations--cmegroup--aemsites.aem.live/education
- Before: https://main--cmegroup--aemsites.aem.live/drafts/nestor/article1
- After: https://issue-24-translations--cmegroup--aemsites.aem.live/drafts/nestor/article1

Issue 24 translations

---

tools/sidekick/config.json

Adding Assets plugin to sidekick
Test URLs:
- Before: https://main--cmegroup--aemsites.aem.live/
- After: https://assets-plugin--cmegroup--aemsites.aem.live/

Adding Assets plugin to sidekick

---

aemedge/scripts/delayed.js
aemedge/scripts/utils.js

Added oneTrust SDK for prod only environments
Fix #14 
Test URLs:
- Before: https://main--cmegroup--aemsites.aem.live/education
- After: https://issue-14--cmegroup--aemsites.aem.live/education

Adding oneTrust SDK

---

tools/sidekick/library.html

Original Sidekick library to preview blocks within DA context for ease of authoring 
**_Preview Blocks Library_** plugin can be tested via opening DA url : https://da.live/edit?ref=preview-blocks#/cmegroup/www/education
sidekick config.json now committed in the config bus looks like below
```
{
"id": "previewblocklibrary",
"title": "Preview Block Library",
"environments": [
"edit"
],
"daLibrary": true,
"includePaths": [
"DA"
],
"experience": "fullsize-dialog",
"icon": "https://da.live/blocks/edit/img/Smock_Images_18_N.svg",
"path": "/tools/sidekick/library.html"
}
```
Test URLs:
- Before: https://main--wwww--cmegroup.aem.live/
- After: https://preview-blocks--www--cmegroup.aem.live/

Original Sidekick library to preview blocks within DA context for ease of authoring 

---

README.md
tools/sidekick/config.json
tools/sidekick/scheduler/scheduler.css
tools/sidekick/scheduler/scheduler.html
tools/sidekick/scheduler/scheduler.js

This PR introduces a new plugin to give the authors an ability to schedule pages for preview, publish, unpublish. 
The mechanism at the backend still remains the same where the cron expressions are committed to crontab sheet under **/cmegroup/www/.helix/crontab**
More details to understand how scheduling works in Edge Delivery, Refer to https://www.aem.live/docs/scheduling
Also, added a note to ReadMe how to go about plugin development for local and DA environments.
Fix #110 
You can see the scheduler plugin in action at https://da.live/edit?ref=issue110-scheduler#/cmegroup/www/drafts/kunwar/test-doc
sidekick config.json now committed in the config bus looks like below
```
{
"id": "scheduler",
"title": "Scheduler", 
"environments": ["edit"],
"daLibrary": true,
"includePaths": ["DA"], …
```

Scheduler Plugin

---

aemedge/blocks/table/table.js

Test URLs:
- Before: https://main--wwww--cmegroup.aem.live/drafts/nawaz/table
- After: https://cell-styles--www--cmegroup.aem.live/drafts/nawaz/table
Inline cell styles will be picked from last paragraph in cell, with format [style-name: value]
We can probably enhance the user experience further with a DA plugin, if needed.

fix: support inline cell styles

---

aemedge/scripts/scripts.js
aemedge/styles/styles.css

In this PR, External Links behavior is added such that authors can override the default link target mechanism (same page) and open in a new window/tab (target=_blank). By default, external urls and pdf links open in a new window/tab
**Author flow**
- Author creates a link in a normal way
- Let it be if they want to open in the same page
- If they want to override, Just select the link and Add extra formatting using ‘**inline code toggle**’
- Preview/Publish
For demo, see this screencast : https://www.loom.com/share/3a4e45c45f974ccdbed0695f4418cb4e
More details on slack discussion : https://adobe-dx-support.slack.com/archives/C06PK80B5A5/p1744905271267909
Test URLs:
- Before: https://main--www--cmegroup.aem.live/drafts/kunwar/links
- After: …

External Links behavior

---

aemedge/blocks/tags-cloud/tags-cloud.js
aemedge/scripts/utils.js

Updates the tags cloud block to show only the tags not included in the exclusions list.
The exclusion list can be configured at:
https://da.live/sheet#/cmegroup/www/eds-config/tags-cloud-exclusions
Fix #238 
Test URLs:
- Before: https://main--www--cmegroup.aem.page/drafts/nestor/article1
- After: https://issue-238-tags-exclusions--www--cmegroup.aem.page/drafts/nestor/article1

Issue 238: Tags exclusions on tags cloud block

---

tools/sidekick/fragments/fragments.js

- Removed the messageManager altogether
- add the close plugin library on fragment select'
Test the plugin 'Fragment Picker Test'  for the new behavior on https://da.live/edit?ref=fragmentfix#/cmegroup/www/drafts/kunwar/fragments/fragment-test
Test URLs:
- After: https://fragmentfix--www--cmegroup.aem.live/

Fragment Picker fix

---

aemedge/blocks/table/table.css
aemedge/blocks/table/table.js
aemedge/scripts/actions/floatingElements.js
aemedge/scripts/alerts/alerts.js
aemedge/scripts/constants/floatingElements.js
aemedge/scripts/constants/index.js
aemedge/scripts/reducers/floatingElements.js
aemedge/scripts/store/store.js

Allow the table block to have a sticky table header and sticky first column (sticky column option can be set for different breakpoints).
Adds the FloatingElements to the store in order to manage the floating elements (navbar, alerts) and place the table header according to the visible floating elements (more floating elements will come in the future).
Fix #152 
Test URLs:
- Before: https://main--www--cmegroup.aem.page/drafts/nestor/tables
- After: https://issue-152-table-block-fixed-row-column--www--cmegroup.aem.page/drafts/nestor/tables

Issue 152 table block fixed row column

---

aemedge/blocks/event-calendar/event-calendar.css
aemedge/blocks/event-calendar/event-calendar.js
aemedge/scripts/utils/misc.js

CUEN-255 - clear x in empty search box
CUEN-254 - date css capitalized fix
CUEN-253 - glitchy service call on clear search box
CUEN-252 - extra BR in texts removed
CUEN-251 - ellipsis for long titles in accordion
Test URLs:
- After: https://calendar-table-fixs--www--cmegroup.aem.live/drafts/ramiro/event-calendar

Calendar table fixs

---

aemedge/scripts/scripts.js
aemedge/styles/styles.css

Fix #236 
Add text highlighting support.
Author highlights text via "inline text"
Author choose highlight bg style via section metadata property "text-highlight"
- New color highlights can be added in the 'options' sheet under https://da.live/sheet#/cmegroup/www/eds-config/sidekick/blocks
Supported via autoblocking decoration
Test URLs:
Before: https://main--www--cmegroup.aem.page/drafts/john/issue-236-text-highlight
After: https://issue236-text-highlighting--www--cmegroup.aem.page/drafts/john/issue-236-text-highlight

Fix #236 Add text highlighting support.

---

aemedge/blocks/brightcove/brightcove.js
aemedge/scripts/course/certificate.js
aemedge/scripts/services/AuthenticationService.js
aemedge/scripts/services/EducationTrackService.js
aemedge/scripts/services/SearchResultsService.js
aemedge/scripts/utils/fetch.js
aemedge/scripts/utils/misc.js

This update reduces the api utility functions down to two (from four) simplifying the need to manually use a specific function based on whether the url contains an absolute or relative url. Functions axiosGet and axiosPost will now check the url for a schema.
Fix #452 
Test URLs:
- Before: https://main--www--cmegroup.aem.live/drafts/chamo/economic-calendar
- After: https://fix-event-cal--www--cmegroup.aem.live/drafts/chamo/economic-calendar

Reduced axios functions simplifying relative to absolute differences

---

aemedge/blocks/brightcove/brightcove.css
aemedge/blocks/brightcove/brightcove.js

Fixed the logic that adds style classes based on the aspectRatio and playlistLocation block configurations.
Fix #455 
Test URLs:
- Before: https://main--www--cmegroup.aem.live/education/courses/building-a-trade-plan
- After: https://issue-455-bc-styles--www--cmegroup.aem.live/education/courses/building-a-trade-plan

Set correct styles for BC video and placeholders

---

aemedge/styles/styles.css

FIx : #365  | Nested bullets are formatted incorrectly
Before: https://main--www--cmegroup.aem.page/education/courses/building-a-trade-plan/methodology-behind-your-trade-plan
After: https://issue-365-bulletSeparation--www--cmegroup.aem.page/education/courses/building-a-trade-plan/methodology-behind-your-trade-plan
Part of the problem was with the nexted elements being auto-wrapped in p element which pulled in conflicting styling for what we needed.
This was a DA issue and a feature toggle (html2md.unspreadLists) was added to CME sites to maintain the original markup (not wrap with p element).
This fixed most of the issue. Only a small style override was required to fix the remaining issue.

Fix #365 Nested bullets are formatted incorrectly

---

.eslintrc.js
aemedge/blocks/brightcove/brightcove.js

Test URLs:
- Before: https://main--www--cmegroup.aem.live/drafts/gmaye/brightcove
- After: https://bc-video-playlist-poster--www--cmegroup.aem.live/drafts/gmaye/brightcove

Add defaultPlaylistPoster field for BC playlists blocks

---

aemedge/blocks/dynamic/course-nav/course-nav.js
aemedge/scripts/utils.js
aemedge/templates/course/course.js
aemedge/templates/lesson/lesson.js

Fix# 475 Preserve hide params on links
Before: https://main--www--cmegroup.aem.page/drafts/daiana/education/courses/course-share?hideHeader=y
After: https://issue-475-preserveHideParamsOnLinks--www--cmegroup.aem.page/drafts/daiana/education/courses/course-share?hideHeader=y
Add util to pull hide params off current page and include them on internal links in that page. Update courses to use the util on its dynamic content creation

Fix# 475 Preserve hide params on links

---

aemedge/scripts/scripts.js
aemedge/styles/styles.css

external-links add subdomain verification
Fix #416 (in part)
Test URLs:
- Before: https://main--www--cmegroup.aem.live/education/2025/commodity-index-trading-webinar-old
- After: https://issue-416-310-external-links--www--cmegroup.aem.live/education/2025/commodity-index-trading-webinar-old
- After: https://issue-416-310-external-links--www--cmegroup.aem.live/education

issue-416-310-external-links add subdomain verification

---

aemedge/scripts/utils.js

add author tags to article tags in tag cloud component
Fix #534
Test URLs:
- Before: https://main--www--cmegroup.aem.live/drafts/ramiro/10-reasons-to-consider-managed-futures
- After: https://article-authors-tag--www--cmegroup.aem.live/drafts/ramiro/10-reasons-to-consider-managed-futures

add author tags to article tags in tag cloud component

---

aemedge/scripts/utils.js
aemedge/templates/lesson-standalone/lesson-standalone.js
aemedge/templates/lesson/lesson.js

- Placing the fragment on template level for both lesson and standalone-lesson to cover for #503 
- added utils function to addFragment blocks
Fix #503 
Test URLs:
- After: https://lesson-template--www--cmegroup.aem.live/education/courses/pork-cutout-futures-product-overview
- After: https://lesson-template--www--cmegroup.aem.live/education/courses/options-on-futures-for-equity-traders/trading-options-on-futures-using-strategies-you-already-know

Add fragments to lesson and standalone template

---

aemedge/templates/article/article.js

Fix #596
Test URLs:
- Before: https://main--www--cmegroup.aem.live/education/articles-and-reports/wti-and-the-changing-dynamics-of-global-crude-oil
- After: https://issue596-authorbyline--www--cmegroup.aem.live/education/articles-and-reports/wti-and-the-changing-dynamics-of-global-crude-oil
- After: https://issue596-authorbyline--www--cmegroup.aem.live/education/articles-and-reports/geo-futures-a-natural-solution

Author line fragmentation  | use "and" before last author in article byline

---

aemedge/blocks/tags-cloud/tags-cloud.js

Fix #611 
Test URLs:
- Before: https://main--www--cmegroup.aem.page/education/articles-and-reports/agriculture-cash-settlement-vs-physical-delivery
- After: https://tag-cloud-fix--www--cmegroup.aem.page/education/articles-and-reports/agriculture-cash-settlement-vs-physical-delivery

fix: render tags in tag cloud only if title exists

---

aemedge/blocks/podcast/podcast.css

Make the podcast block background-color specific to the block. Currently it is interfering with podcast pages with have a subtemplate (podcast article)
Fix #636 
Test URLs:
- Before: https://main--www--cmegroup.aem.page/drafts/kunwar/a-discussion-with-cap-intro-and-managers
- After: https://issue636-podcast-backgroundcolor--www--cmegroup.aem.page/drafts/kunwar/a-discussion-with-cap-intro-and-managers

Make the podcast block background-color specific to the block

---

aemedge/styles/styles.css

Fix [662](https://github.com/aemsites/cmegroup/issues/662)
Test URLs:
- Before: https://main--www--cmegroup.aem.page/drafts/daiana/education/courses/course-share
- After: https://issue-662-sharethis--www--cmegroup.aem.page/drafts/daiana/education/courses/course-share

issue-662-sharethis overlapped by the navbar

---

aemedge/scripts/utils/env.js

Force www content to continue hitting beta services.
Test URLs:
- After: https://login-updates-fix--www--cmegroup.aem.live/

fix(cuwst-439): force www continue to hit beta svcs

---

aemedge/scripts/modules/Authentication.js
aemedge/scripts/utils/env.js

Send correct target login process url to SAML based on the domain on which the user is logging in.
Test URLs:
- After: https://login-updates--www--cmegroup.aem.live/

fix(cuwst-439): send correct target url based on the domain

---

aemedge/blocks/search/search-results/search-results.js
aemedge/scripts/utils.js

Fixes the issue in filter items count (facets count) by doing some improvements:
1. Perform an extra call to the API for each filter with selected values, but excluding the values on that filter to get the full count of each.
2. Include debounce function with 500ms of delay on filters selection to avoid excessive API calls.
3. Track the last call to search function to avoid out of sync updates.
Fix #678 
Test URLs:
- Before: https://main--www--cmegroup.aem.page/drafts/nestor/browse-all
- After: https://issue-678-search-block-issue--www--cmegroup.aem.page/drafts/nestor/browse-all

Issue 678 search block issue
